# scripts/utils/gen_test_validate.py
import os
import sys


def main():
    repo_root = os.environ.get("REPO_ROOT")
    if not repo_root:
        print("REPO_ROOT environment variable not set")
        sys.exit(1)
    os.chdir(repo_root)

    files = sys.argv[1:]
    if not files:
        print("Specify files to check")
        sys.exit(1)

    test_dir = os.path.join(repo_root, "tests")
    os.makedirs(test_dir, exist_ok=True)
    test_file = os.path.join(test_dir, "test_validate_files.py")
    with open(test_file, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by gen_test_validate.py\n")
        f.write("import os\n\n")
        f.write("files_to_check = [\n")
        for p in files:
            f.write(f"    {p!r},\n")
        f.write("]\n\n")
        f.write("def test_files_exist():\n")
        f.write("    for path in files_to_check:\n")
        f.write("        assert os.path.exists(path), f'{path} not found'\n")
    print("Generated", test_file)


if __name__ == "__main__":
    main()
