name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check FlatBuffers schema
        run: flatc --strict-json --proto ./flatbuffers/ephemeral_session.fbs
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run FFI Tests
        run: cargo test --test ffi_test
      - name: Run FFI Security Tests
        run: cargo test --test ffi_security_test
      - name: Run Python Secure Bridge Tests
        run: python -m unittest tests/test_secure_bridge.py
